Numpy - Beginner


 Create a 1D NumPy array with integers from 10 to 50

In [ ]:
import numpy as np
arr = np.arange(10, 51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Generate a 3x3 array of random numbers between 0 and 1.


In [ ]:
rand_arr = np.random.rand(3, 3)
print(rand_arr)


[[0.03137348 0.45641437 0.25634026]
 [0.97779015 0.64369358 0.3619061 ]
 [0.82339083 0.87309358 0.76322146]]


Find the mean, median, and standard deviation of the following array:
arr = np.array([1, 2, 3, 4, 5, 6]).


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

mean_val = np.mean(arr)
median_val = np.median(arr)
std_val = np.std(arr)

print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_val)


Mean: 3.5
Median: 3.5
Standard Deviation: 1.707825127659933


Replace all even numbers in a NumPy array with -1.
Example: arr = np.array([1, 2, 3, 4, 5, 6])


In [ ]:
arr2 = np.array([1, 2, 3, 4, 5, 6])
arr2[arr2 % 2 == 0] = -1
print(arr2)


[ 1 -1  3 -1  5 -1]


NumPy - Intermediate

Create a 4x4 matrix with random integers between 1 and 100 and replace all elements greater than 50 with 50.


In [5]:
import numpy as np
arr = np.random.randint(1, 101, (4, 4))
arr[arr > 50] = 50
print(arr)



[[44 50 23 50]
 [ 3 36 50 33]
 [50 20 50 13]
 [50  1 32 50]]


Flatten a 2D array into a 1D array using both ravel() and flatten() methods. Explain the difference.


In [ ]:
arr = np.array([[1,5],[3,8]])
arr_ravel = arr.ravel()
print(arr_ravel)
#linked to original

[1 5 3 8]


In [ ]:
arr = np.array([[1,5],[3,8]])
arr_flatten = arr.flatten()
print(arr_flatten)
#saves a copy

[1 5 3 8]


Compute the dot product of two matrices:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

dot_product = np.dot(A, B)
print(dot_product)


[[19 22]
 [43 50]]


Extract the unique elements from the following array and count their occurrences:
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])


In [7]:
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])
unique , counts = np.unique(arr, return_counts=True)
print(unique)
print(counts)

#

[1 2 3 4 5]
[1 2 1 3 1]


NumPy - Advanced


Implement matrix multiplication manually (without using np.dot or @).


In [1]:
import numpy as np

A = np.array([[10, 20], [3, 4]])
B = np.array([[6, 2], [2, 3]])

# Manually compute A x B
result = np.zeros((A.shape[0], B.shape[1]))

for i in range(A.shape[0]):
    for j in range(B.shape[1]):
        for k in range(A.shape[1]):
            result[i][j] += A[i][k] * B[k][j]

print(result)

## recheck 


[[100.  80.]
 [ 26.  18.]]


Create a 3D array of shape (3, 4, 5) filled with random integers. Normalize the array values to the range 0-1.


In [ ]:
arr3d = np.random.randint(0, 100, (3, 4, 5))
normalized = (arr3d - arr3d.min()) / (arr3d.max() - arr3d.min())

print("Original array:\n", arr3d)
print("Normalized array:\n", normalized)
# normalization formula = (x−min)/(max−min) (always between 0 and 1)


Original array:
 [[[ 6 61 78 81 22]
  [83 66 58 15 83]
  [28 47 71 58 65]
  [95 86 87 59 40]]

 [[32 46 21 43 81]
  [69 73  3 71 36]
  [60 67 26 81 41]
  [60 47 78 50 69]]

 [[51 10 21 32 65]
  [64  6 94 68 10]
  [39 69 92 36 61]
  [54 41 76 17 83]]]
Normalized array:
 [[[0.0326087  0.63043478 0.81521739 0.84782609 0.20652174]
  [0.86956522 0.68478261 0.59782609 0.13043478 0.86956522]
  [0.27173913 0.47826087 0.73913043 0.59782609 0.67391304]
  [1.         0.90217391 0.91304348 0.60869565 0.40217391]]

 [[0.31521739 0.4673913  0.19565217 0.43478261 0.84782609]
  [0.7173913  0.76086957 0.         0.73913043 0.35869565]
  [0.61956522 0.69565217 0.25       0.84782609 0.41304348]
  [0.61956522 0.47826087 0.81521739 0.51086957 0.7173913 ]]

 [[0.52173913 0.07608696 0.19565217 0.31521739 0.67391304]
  [0.66304348 0.0326087  0.98913043 0.70652174 0.07608696]
  [0.39130435 0.7173913  0.9673913  0.35869565 0.63043478]
  [0.55434783 0.41304348 0.79347826 0.15217391 0.86956522]]]


Write a function to calculate the inverse of a matrix (handle errors if the matrix is non-invertible).


In [ ]:
def inverse_matrix(mat):
    try:
        inv = np.linalg.inv(mat)
        return inv
    except np.linalg.LinAlgError:
        return "Matrix is not invertible."

# Example
mat = np.array([[1, 2], [3, 4]])
print(inverse_matrix(mat))

#try and except , tries for all inputs except said condition.


[[-2.   1. ]
 [ 1.5 -0.5]]


Simulate a Markov chain with a given transition matrix.


In [2]:
import numpy as np  # To use random choice

# Step 1: Define the transition matrix
# Row 0 = Sunny, Row 1 = Rainy
# [Sunny to Sunny, Sunny to Rainy]
# [Rainy to Sunny, Rainy to Rainy]
transition_matrix = [
    [0.8, 0.2],  # If it's Sunny today
    [0.4, 0.6]   # If it's Rainy today
]

# Step 2: Choose a starting state (0 = Sunny, 1 = Rainy)
current_state = 0  # Let's say we start with Sunny

# Step 3: Decide how many steps to simulate
steps = 10

# Step 4: Store the result
states = [current_state]

# Step 5: Simulate the chain
for _ in range(steps):
    # Get the probabilities for the current state
    probs = transition_matrix[current_state]

    # Choose the next state: 0 or 1
    next_state = np.random.choice([0, 1], p=probs)

    # Add it to the list
    states.append(next_state)

    # Move to next state
    current_state = next_state

# Step 6: Print the state sequence
print("State sequence:", states)


#understand


State sequence: [0, np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(1), np.int64(0), np.int64(1), np.int64(1), np.int64(0)]


Pandas - Beginner


Create a DataFrame from a dictionary:

data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35], 'City': ['New York', 'Los Angeles', 'Chicago']}


1.Select all rows where "Age" is greater than 28.

2.Add a new column "Salary" with values [50000, 60000, 70000] to the DataFrame created above.

3.Rename the column "City" to "Location".


In [5]:
!pip install pandas  # Install pandas if not already installed
import pandas as pd  # pandas helps with table-like data


data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}


df = pd.DataFrame(data)
print(df)



[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: C:\Users\sasha\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
ERROR: Invalid requirement: '#': Expected package name at the start of dependency specifier
    #
    ^


ModuleNotFoundError: No module named 'pandas'

In [6]:
import pandas as pd  # pandas helps with table-like data


data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}


df = pd.DataFrame(data)
print(df)


ModuleNotFoundError: No module named 'pandas'

In [10]:
filtered_df = df[df['Age'] > 28]
print(filtered_df)


      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [11]:
df['Salary'] = [50000, 60000, 70000]
print(df)


      Name  Age         City  Salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000


In [14]:
df = df.rename(columns={'City':'Location'})
print(df)

      Name  Age     Location  Salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000


Pandas - Intermediate

Load a CSV file (e.g., sample.csv) into a DataFrame and display the first 10 rows.

1.Group the DataFrame by a specific column (e.g., "City") and calculate the mean of another column (e.g., "Salary").

2.Handle missing data in a DataFrame by:

3.Replacing NaN values with the mean of the column.
Dropping rows with NaN values.

4.Sort the DataFrame by multiple columns, e.g., by "Age" (ascending) and "Salary" (descending).


In [ ]:
import pandas as pd

df = pd.read_csv('sample.csv')   # Load the CSV into a DataFrame
print(df.head(10))               # Show the first 10 rows


      Name   Age         City   Salary
0    Alice  25.0     New York  50000.0
1      Bob  30.0  Los Angeles  60000.0
2  Charlie  35.0      Chicago  70000.0
3    David  28.0     New York      NaN
4      Eva  40.0  Los Angeles  75000.0
5    Frank  30.0      Chicago  62000.0
6    Grace  32.0          NaN  58000.0
7    Helen  27.0      Chicago  61000.0
8      Ian   NaN     New York  54000.0
9    Julia  29.0  Los Angeles  69000.0


In [ ]:
grouped = df.groupby('City')['Salary'].mean()
print(grouped)


City
Chicago        64333.333333
Los Angeles    68000.000000
New York       55370.370370
Name: Salary, dtype: float64


In [20]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
print(df)

      Name  Age     Location  Salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000


In [18]:
df = df.sort_values(by=['Age', 'Salary'], ascending=[True, False])
print(df)


      Name  Age     Location  Salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000


Pandas advanced

Pandas

1.Perform a join operation between two DataFrames:
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'ID': [1, 2, 4], 'Score': [85, 90, 95]})

2.Pivot a DataFrame with columns "Date," "City," and "Temperature" into a wide format where cities are columns.

3.Use apply() to create a new column in a DataFrame based on complex logic (e.g., categorize "Age" into bins: child, adult, senior).

4.Identify duplicate rows in a DataFrame and drop all but the first occurrence.


In [ ]:
import pandas as pd

# Create first DataFrame
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

# Create second DataFrame
df2 = pd.DataFrame({
    'ID': [1, 2, 4],
    'Score': [85, 90, 95]
})

# Perform an inner join on 'ID' column
joined = pd.merge(df1, df2, on='ID', how='inner')
print(joined)

#inner means everything that align

   ID   Name  Score
0   1  Alice     85
1   2    Bob     90


In [ ]:
data = {
    'Date': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02'],
    'City': ['New York', 'Los Angeles', 'New York', 'Los Angeles'],
    'Temperature': [30, 60, 32, 58]
}

df = pd.DataFrame(data)

# Pivot so each city is a column
pivoted = df.pivot(index='Date', columns='City', values='Temperature')
print(pivoted)


City        Los Angeles  New York
Date                             
2024-01-01           60        30
2024-01-02           58        32


In [ ]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [12, 25, 70, 40]
})

def categorize_age(age):
    if age < 18:
        return 'Child'
    elif age < 60:
        return 'Adult'
    else:
        return 'Senior'

#  To Apply the function to create a new column
df['Category'] = df['Age'].apply(categorize_age)
print(df)


      Name  Age Category
0    Alice   12    Child
1      Bob   25    Adult
2  Charlie   70   Senior
3    David   40    Adult


In [ ]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob'],
    'Age': [25, 30, 25, 35, 30]
})

# Find duplicates
duplicates = df[df.duplicated()]
print("Duplicate rows:\n", duplicates)

# Drop all but the first occurrence
df_cleaned = df.drop_duplicates()
print("After dropping duplicates:\n", df_cleaned)


Duplicate rows:
     Name  Age
2  Alice   25
4    Bob   30
After dropping duplicates:
       Name  Age
0    Alice   25
1      Bob   30
3  Charlie   35
